### ISSUE TITLE
Code profiling

### ISSUE THREAD

**Issue by rikba** [ethz-asl/ethz_piksi_ros#98]
The Piksi multi ROS driver occupies too much CPU. We need to profile the code and either fix the leak or implement a minimum cpp driver for sensitive tasks. @stlucas44

**Comment by rikba** [comment]
Currently it uses up about 10% of a i7-7820HQ core.

![Screenshot_2019-09-26_12-42-26](https://user-images.githubusercontent.com/11293852/65682368-217d0d00-e05b-11e9-9dfa-b7765359a216.png)

**Comment by michaelpantic** [comment]
Tipps to profile:

To install:

sudo pip install yappi
sudo apt-get install kcachegrind


To profile rosnodes, use a launch-prefix inside the roslaunch file:
launch-prefix="yappi -b -f callgrind -o /tmp/yappi.out"

(where /tmp/yappi.out is the output of the profiler)

To then examine the profiler files, use cachegrind:
kcachegrind /tmp/yappi.out

See also https://kcachegrind.github.io/html/Home.html

**Comment by michaelpantic** [comment]
One additional note:

Profilers sometimes don't like it if the program to be profiled is just killed / ctrl-c' ed like we do it with rosnodes. To gracefully exit, you can also add an "Exit Service", thats just a rosservice that shuts down the node once called.

**Comment by stlucas44** [comment]
The profiling is performed in a first iteration by adding the proposed launch-prefix:
launch-prefix= "yappi -b -f callgrind  -o /home/lucas/tmp/test.out"

The results were difficult to interpret because of confusing visualization. One assumes that the framer as well as the handler, which is operating the framer, are implemented in a slow manner. 

![screenshot_piksi_multi_prelauch_profiling](https://user-images.githubusercontent.com/33226322/66210577-77386180-e6ba-11e9-9dae-63518c0bf717.png)

**Comment by rikba** [comment]
CPP driver performs way better and to be used in future.
